### ISSUE TITLE
APP freeze/hangs when using in uitableview cell for multiple videos

### ISSUE THREAD

**Issue by jitesh-sharma** [changsanjiang/SJMediaCacheServer#18]
getting a console error every time during fast scroll UITableview. Every cell contains a video object configure with library playback URL (**let playBackUrl = SJMediaCacheServer.shared().playbackURL(with: url**)) and play after scroll didEndScrolling. after 2 3 videoes app freezes. No response and throw an error below;
**Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future**

**Comment by changsanjiang** [comment]
@jitesh-sharma  I fixed this warning in the [new version 1.5.0](https://github.com/changsanjiang/SJMediaCacheServer/releases/tag/1.5.0)

**Comment by jitesh-sharma** [comment]
The warning is gone now, but the app freezing issue still there. When we are playing 2 3 videos on the visible screen (in different UitableviewCells or sometimes in single Cell 2 videos are playing) and scroll up and down then the app freeze/hangs. Sometimes when we navigate to different screens from the video screen then the app freeze. Don't know what the main issue behind it but its only happening when we are using the playback URL of SJMediaCacheServer class. 

**Implementation of UItableviewCell and UIViewController,** 

**UITableViewCell Code**
    override func **prepareForReuse**() {
        super.prepareForReuse()
        videoUrl = nil
        player = nil
        playerLayer = nil
        playerItem = nil
    }

    func **setupPlayerView**() {
        player = AVPlayer()
        if let urlString = videoUrl, let url = URL(string: urlString) {
            if let playBackUrl = SJMediaCacheServer.shared().playbackURL(with: url) {
                playerItem = AVPlayerItem(url: playBackUrl)
            } else {
                playerItem = AVPlayerItem(url: url)
            }
        }
        playerLayer = AVPlayerLayer(player: player)
        playerLayer?.frame = view_s1_v1_PlayerView.bounds
        view_s1_v1_PlayerView.layer.addSublayer(playerLayer!)
        player?.replaceCurrentItem(with: playerItem)
    }

    func **playVideo**() {
        player?.play()
}

    func **pauseVideo**() {
        player?.pause()
    }


 **and then play() pause() from UIViewcontroller's** 
  
  override func **scrollViewDidEndDecelerating**(_ scrollView: UIScrollView) {
        checkVisibleCell()
    }

    func tableView(_ tableView: UITableView, **didEndDisplaying** cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        if let videoCell = cell as? LRVideoMeshTableViewCell {
            videoCell.pauseVideo()
        }
    }

    func **checkVisibleCell**() {
        let visibleCells = tv_videoCategoryList.visibleCells.compactMap { $0 as? LRVideoMeshTableViewCell }
        
        guard visibleCells.count > 0 else { return }
        
        let visibleFrame = CGRect(x: 0, y: tv_videoCategoryList.contentOffset.y, width: tv_videoCategoryList.bounds.width, height: tv_videoCategoryList.bounds.height)

        let visibleCell = visibleCells
            .filter { visibleFrame.intersection($0.frame).height >= $0.frame.height / 2 }
            .first
        
        visibleCell?.playVideo()
    }


@changsanjiang please let me know if I am doing wrong here or suggest if any changes needed in the library to fix this.
